# Generated by Django 4.2.1 on 2023-05-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_room_skill_alter_message_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='skll',
        ),
    ]
