# Generated by Django 4.2.1 on 2023-05-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_room_message_skll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='skll',
            new_name='skill',
        ),
    ]
