# Generated by Django 4.2.1 on 2023-05-26 14:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Tool',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='skill',
            new_name='tool',
        ),
    ]
