# Generated by Django 4.2.1 on 2023-06-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_skill_tool_rename_skill_message_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stars',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
