# Generated by Django 4.2.1 on 2023-06-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_project_stars_tool_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stars',
            field=models.CharField(default='3', max_length=10),
        ),
        migrations.AlterField(
            model_name='tool',
            name='stars',
            field=models.CharField(default='3', max_length=10),
        ),
    ]
